library(shiny) 
library(sf)
library(leaflet)
library(readr)
library(dplyr)

source("topVuln.R")
source("subsetVulnData.R")
source("vulnMap.R")
source("topDriversTable.R")
source("subsetCharitiesData.R")
source("charitiesTable.R")
source("charitiesMap.R")
source("emergency_planning_tool.R")

vuln_scores_flood <- read_rds("data/flooding_vuln_scores_sf.rds")
vuln_drivers_flood <- read_rds("data/flooding_drivers.rds")
charities_ltla_lookup <- read_rds("data/charities_ltla_lookup.rds")
charities_data <- read_rds("data/charities_list_latlong.rds")

emergency_planning_tool()
