library(shiny) 
library(sf)
library(leaflet)
library(readr)
library(dplyr)
library(shinyWidgets)

source("selectAreaDropdown.R")
source("selectedAreaMap.R")
source("topVuln.R")
source("subsetVulnData.R")
source("vulnMap.R")
source("topDriversTable.R")
source("subsetCharitiesData.R")
source("subsetCharitiesDataCategories.R")
source("charitiesTable.R")
source("charitiesMap.R")
source("explanation.R")
source('floodingLicence.R')

vuln_scores_flood <- read_rds("data/flooding_vuln_scores_sf.rds")
vuln_drivers_flood <- read_rds("data/flooding_drivers_v2.rds")
charities_ltla_lookup <- read_rds("data/charities_ltla_lookup.rds")
charities_data <- read_rds("data/charities_list_latlong.rds")
lsoa_ltla_lookup <- read_rds("data/lsoa_ltla_lookup.rds")
boundaries_ltlas <- read_rds("data/boundaries_ltlas.rds")
charities_categories_data <- read_rds("data/charities_categories.rds")


source("emergency_planning_tool.R")
emergency_planning_tool()

